modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"

[[mods]]
modId = "configured_neoforge_command_adapter"
version = "${version}"
displayName = "Configured Neoforge Command Adapter"
authors = "Clickism"
description = '''
Configured Neoforge Command Adapter Module.
'''

[[dependencies.configured_neoforge_command_adapter]]
modId = "neoforge"
type = "required"
versionRange = "*"
side = "BOTH"

[[dependencies.configured_neoforge_command_adapter]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
side = "BOTH"