license = "GPL-3.0"
issueTrackerURL = "https://github.com/Clickism/Configured/issues"
showAsResourcePack = false

[[mods]]
modId = "configured-neoforge-command-adapter"
version = "${version}"
displayName = "Configured Neoforge Command Adapter"
logoFile = "assets/clickmobs/icon.png"
authors = "Clickism"
description = "Configured Neoforge Command Adapter Module."

[[dependencies.configured-neoforge-command-adapter]]
modId = "neoforge"
type = "required"
versionRange = "*"
side = "BOTH"

[[dependencies.configured-neoforge-command-adapter]]
modId = "minecraft"
type = "required"